/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const DonationSubmission = IDL.Record({
  'id' : SubmissionId,
  'donationType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Opt(IDL.Text),
});
export const VolunteerSubmission = IDL.Record({
  'id' : SubmissionId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const SubmissionResult = IDL.Record({
  'id' : SubmissionId,
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getDonations' : IDL.Func([], [IDL.Vec(DonationSubmission)], ['query']),
  'getVolunteers' : IDL.Func([], [IDL.Vec(VolunteerSubmission)], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [SubmissionResult],
      [],
    ),
  'submitDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [SubmissionResult],
      [],
    ),
  'submitVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const DonationSubmission = IDL.Record({
    'id' : SubmissionId,
    'donationType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Opt(IDL.Text),
  });
  const VolunteerSubmission = IDL.Record({
    'id' : SubmissionId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const SubmissionResult = IDL.Record({
    'id' : SubmissionId,
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getDonations' : IDL.Func([], [IDL.Vec(DonationSubmission)], ['query']),
    'getVolunteers' : IDL.Func([], [IDL.Vec(VolunteerSubmission)], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [SubmissionResult],
        [],
      ),
    'submitDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [SubmissionResult],
        [],
      ),
    'submitVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };