/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : SubmissionId,
  'subject' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : [] | [string],
}
export interface DonationSubmission {
  'id' : SubmissionId,
  'donationType' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
  'amount' : [] | [string],
}
export type SubmissionId = bigint;
export interface SubmissionResult {
  'id' : SubmissionId,
  'message' : string,
  'success' : boolean,
}
export type Timestamp = bigint;
export interface VolunteerSubmission {
  'id' : SubmissionId,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'availability' : string,
  'message' : string,
  'phone' : string,
  'skills' : string,
}
export interface _SERVICE {
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getDonations' : ActorMethod<[], Array<DonationSubmission>>,
  'getVolunteers' : ActorMethod<[], Array<VolunteerSubmission>>,
  'submitContact' : ActorMethod<
    [string, string, string, string, [] | [string]],
    SubmissionResult
  >,
  'submitDonation' : ActorMethod<
    [string, string, string, string, [] | [string], string],
    SubmissionResult
  >,
  'submitVolunteer' : ActorMethod<
    [string, string, string, string, string, string],
    SubmissionResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];