/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VolunteerSubmission {
    id: SubmissionId;
    name: string;
    submittedAt: Timestamp;
    email: string;
    availability: string;
    message: string;
    phone: string;
    skills: string;
}
export interface DonationSubmission {
    id: SubmissionId;
    donationType: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
    phone: string;
    amount?: string;
}
export type Timestamp = bigint;
export interface SubmissionResult {
    id: SubmissionId;
    message: string;
    success: boolean;
}
export interface ContactSubmission {
    id: SubmissionId;
    subject: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
    phone?: string;
}
export type SubmissionId = bigint;
export interface backendInterface {
    getContacts(): Promise<Array<ContactSubmission>>;
    getDonations(): Promise<Array<DonationSubmission>>;
    getVolunteers(): Promise<Array<VolunteerSubmission>>;
    submitContact(name: string, email: string, subject: string, message: string, phone: string | null): Promise<SubmissionResult>;
    submitDonation(name: string, email: string, phone: string, donationType: string, amount: string | null, message: string): Promise<SubmissionResult>;
    submitVolunteer(name: string, phone: string, email: string, skills: string, availability: string, message: string): Promise<SubmissionResult>;
}
import type { ContactSubmission as _ContactSubmission, DonationSubmission as _DonationSubmission, SubmissionId as _SubmissionId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getContacts(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonations(): Promise<Array<DonationSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonations();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonations();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteers(): Promise<Array<VolunteerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteers();
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitDonation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDonation(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async submitVolunteer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_ContactSubmission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactSubmission): ContactSubmission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DonationSubmission_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationSubmission): DonationSubmission {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubmissionId;
    subject: string;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    message: string;
    phone: [] | [string];
}): {
    id: SubmissionId;
    subject: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
    phone?: string;
} {
    return {
        id: value.id,
        subject: value.subject,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        phone: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubmissionId;
    donationType: string;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    message: string;
    phone: string;
    amount: [] | [string];
}): {
    id: SubmissionId;
    donationType: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    message: string;
    phone: string;
    amount?: string;
} {
    return {
        id: value.id,
        donationType: value.donationType,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        phone: value.phone,
        amount: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactSubmission>): Array<ContactSubmission> {
    return value.map((x)=>from_candid_ContactSubmission_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationSubmission>): Array<DonationSubmission> {
    return value.map((x)=>from_candid_DonationSubmission_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
